title: LZL Engineering
logo: 
email: info@lzlengineering.com
description: >- # this means to ignore newlines until "baseurl:"
  Fluidized Bed Particle Processing Solutions
show_downloads:
google_analytics:
domain: lzlengineering.com
url: "https://lzlengineering.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/docs" # the subpath of your site, e.g. /blog
# twitter_username: jekyllrb
# github_username:  jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache

