# Gemfile

source 'https://rubygems.org'

gem "jekyll", "~> 4.2"

group :jekyll_plugins do
  gem "jekyll-timeago", "~> 0.13.1"
end

gem "json", "~> 2.7"

gem "jekyll-feed", "~> 0.17.0"


gem "jekyll-remote-theme", "~> 0.4.3"

gem "jekyll-seo-tag", "~> 2.8"
